version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ping-websites"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ak9zshzaxj43"
s3_prefix = "ping-websites"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
