AWSTemplateFormatVersion: 2010-09-09
Description: >-
  ping-websites

Transform:
- AWS::Serverless-2016-10-31

Resources:  
  ScheduledEventLogger:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function that logs the status code of websites to dynamoDB.
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Handler: src/index.handler
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 * * * ? *)
      MemorySize: 128
      Timeout: 100